/* MultPrinter
Direitos autorais (c) 2019 CDAS

Arquivo mpuilang.h 
*/



#define TEXT_MULT_PRINTER  "MULTI PRINTER"
#define TEXT_PRINTER       "Impressora"
#define TEXT_WAIT          "Aguarde"
#define TEXT_CHECKING      "Verificando"
#define TEXT_NOTICE        "Aviso"
#define TEXT_MIDIA_DETECT  "Midia Detectada"  
#define TEXT_NOT_MIDIA_DETECT "Midia não detectada"
#define TEXT_ERROR          "Error"
#define TEXT_PLACE_MIDIA     "Coloque a midia"
#define TEXT_PRESS_BACK       "Pressione Back"
#define TEXT_PRINTING_MIDIA   "Imprimindo Midia"
#define TEXT_EJECTING         "Ejetando"  
#define TEXT_PRINTING          "Imprimindo"
#define TEXT_LAST_SECOND      "Segunda Passada"
#define TEXT_RETURNING        "Retornando" 
#define TEXT_MANUAL_MODE      "Modo Manual" 
#define TEXT_AUTOMATIC_MODE    "Modo Automatico"
#define TEXT_CALLING           "Ligando"
#define TEXT_STARTING          "Iniciando"
#define TEXT_LOADING_INK      "Carregando Tinta"
#define TEXT_ERROR_MIDIA       "Error Midia"
#define TEXT_OFF               "Desligada"
#define TEXT_ON                "Ligado"
#define TEXT_TURNING_OFF       "Desligando"
#define TEXT_GENERAL_ERROR    "Error Geral"
#define TEXT_PAPER            "Papal" 
#define TEXT_RESET_SPONGE     "Resetar Esponja"
#define TEXT_INK_ENDING       "Tinta acabando"
#define TEXT_INK_IS_OVER      "Tinta Acabou"
#define TEXT_CANCELING        "Cancelando"
#define TEXT_SD_CARD_CHECK       "SD CARD CHECK"
#define TEXT_SD_CARD_CHECK_INI   "Iniciando SD CARD.."
#define TEXT_SD_CARD_CHECK_FAIL   "Falha na inicialização !!!"
#define TEXT_SD_CARD_COMPLETE  "Inicialização concluída"
#define TEXT_SD_CARD_MAKEDIR  "Criando o diretório ..."
#define TEXT_SD_CARD_ENTERFILE  "Digite o nome do arquivo / diretório:"
#define TEXT_SD_CARD_ERROR_NAMEFILE "Erro: nome do arquivo duplicado ..."
#define TEXT_SD_CARD_ERROR_NAMEDIR  "Erro: nome do diretório duplicado ..."
#define TEXT_SD_CARD_CHANGE_DIR "Alterar o diretório para ..."
#define TEXT_SD_CARD_REMOVE_FILE "Remover o arquivo ..."
#define TEXT_SD_CARD_REMOVE_DIR "Remover o diretório ..."
#define TEXT_SD_CARD_ERROR_OPENFILE  "Erro ao abrir o arquivo"
#define TEXT_SD_CARD_NOT        "Cartao não detectado"    
#define TEXT_SD_CARD_OK         "OK!"
#define TEXT_SD_CARD_READ       "lendo..."
#define TEXT_SD_CARD_WRITE     "Escrevando..."
